analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
  plugins:
    - custom_lint
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    avoid_print: false