name: onboarding_assignment
description: "Flutter team on-boarding assignment."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-66.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_config: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  json_serializable: ^6.7.1
  freezed: ^2.5.2

flutter:
  uses-material-design: true